packages:
  - .
  - example
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.3.0
  vite-plus: ^0.3.0
  vitest: ^4.1.11
overrides:
  '@cloudflare/workers-types': ^5.20260826.1
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
