import {
  createPostHead,
  createPostLoader,
  type BlogPostLoaderProps,
} from 'void-blog/server';
// Generated by void-blog.
import allPosts from '../../src/posts/AllPosts.ts';
import blogConfig from '../../src/posts/BlogConfig.ts';

export type Props = BlogPostLoaderProps;

export const prerender = true;

export function getPrerenderPaths() {
  return allPosts.map(({ slug }) => ({ slug }));
}

export const loader = createPostLoader({ posts: allPosts });
export const head = createPostHead(blogConfig);
