import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join, relative } from 'node:path';
import { styleText } from 'node:util';
import { Resvg } from '@resvg/resvg-js';
import matter from 'gray-matter';
import { createElement } from 'react';
import satori from 'satori';
import { toGeneratedConfig } from '../lib/config.ts';
import getPostTypeColorName from '../lib/getPostTypeColorName.ts';
import type {
  BlogGenerateContentOptions,
  BlogGeneratedConfig,
  BlogOGImageTheme,
  BlogPost,
  BlogRouteComponentImports,
} from '../lib/Types.ts';
import { getAllPublishedPosts } from '../server.ts';
import { readPosts } from './posts.ts';

const generatedHeader = '// Generated by void-blog.\n';

const readFileIfExists = (path: string) => {
  try {
    return readFileSync(path, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null;
    }

    throw error;
  }
};

const writeFileIfChanged = (path: string, content: string) => {
  if (readFileIfExists(path) !== content) {
    writeFileSync(path, content, 'utf8');
  }
};

const toImportPath = (fromDir: string, toFile: string) => {
  const path = relative(fromDir, toFile).replaceAll('\\', '/');
  return path.startsWith('.') ? path : `./${path}`;
};

const escapeXml = (value: string) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');

const serialize = (value: unknown) => JSON.stringify(value, null, 2);

const toFsImportPath = (path: string) => {
  const normalizedPath = path.replaceAll('\\', '/');

  return `/@fs${normalizedPath.startsWith('/') ? '' : '/'}${normalizedPath}`;
};

export const generatePostsModule = (posts: ReadonlyArray<BlogPost>) =>
  `${generatedHeader}export default ${serialize(posts)};
`;

export const generateBlogConfigModule = (config: BlogGeneratedConfig) =>
  `${generatedHeader}import { defineBlog } from 'void-blog';
export default defineBlog(${serialize(config)});
`;

export function generatePinnedPostModule({
  config,
  pinnedPost,
  root,
}: {
  config: BlogGeneratedConfig;
  pinnedPost: BlogPost | undefined;
  root: string;
}) {
  return pinnedPost
    ? `${generatedHeader}import content, { tableOfContents } from ${serialize(toFsImportPath(join(root, config.contentDir, `${pinnedPost.slug}.mdx`)))};
import allPosts from 'void-blog/posts';

const metadata = allPosts.find((post) => post.slug === ${serialize(pinnedPost.slug)});

if (!metadata) {
  throw new Error('Pinned post metadata not found.');
}

export default {
  ...metadata,
  content,
  tableOfContents: tableOfContents ?? null,
};
`
    : `${generatedHeader}export default null;
`;
}

function generatePostPages({
  config,
  configImport,
  posts,
  root,
  routeComponentImports,
}: {
  config: BlogGeneratedConfig;
  configImport?: string;
  posts: ReadonlyArray<BlogPost>;
  root: string;
  routeComponentImports?: BlogRouteComponentImports;
}) {
  const routeDir = config.routeBase.replace(/^\/+/, '');
  const pagesDir = join(root, 'pages', routeDir);
  const configPath = configImport
    ? join(root, configImport)
    : 'void-blog/blog-config';
  const postRouteImport = routeComponentImports?.post
    ? `import BlogPostRoute from '${toImportPath(pagesDir, join(root, routeComponentImports.post))}';`
    : "import { BlogPostRoute } from 'void-blog/react';";
  const routeAndConfigImports = routeComponentImports?.post
    ? `import blogConfig from '${configImport ? toImportPath(pagesDir, configPath) : configPath}';
${postRouteImport}`
    : `${postRouteImport}
import blogConfig from '${configImport ? toImportPath(pagesDir, configPath) : configPath}';`;
  const contentDirImportPath = toImportPath(
    pagesDir,
    join(root, config.contentDir),
  );

  mkdirSync(pagesDir, { recursive: true });

  writeFileIfChanged(
    join(pagesDir, '[slug].tsx'),
    `import {
  lazy,
  Suspense,
  type ComponentType,
  type LazyExoticComponent,
} from 'react';
${generatedHeader}import type { BlogPostContent, BlogTableOfContents } from 'void-blog';
${routeAndConfigImports}
import type { Props } from './[slug].server.ts';

type MdxModule = Readonly<{
  default: BlogPostContent;
  tableOfContents?: BlogTableOfContents | null;
}>;

type PostRouteComponent =
  | ComponentType<Props>
  | LazyExoticComponent<ComponentType<Props>>;

const serverPosts = import.meta.env.SSR
  ? import.meta.glob<MdxModule>('${contentDirImportPath}/*.mdx', {
      eager: true,
    })
  : ({} as Record<string, MdxModule>);
const clientPosts = import.meta.glob<MdxModule>('${contentDirImportPath}/*.mdx');

const createPostRoute = (mod: MdxModule): ComponentType<Props> =>
  function PostRoute(props) {
    return (
      <BlogPostRoute
        {...props}
        config={blogConfig}
        content={mod.default}
        tableOfContents={mod.tableOfContents ?? null}
      />
    );
  };

const serverRoutes = Object.fromEntries(
  Object.entries(serverPosts).map(([key, mod]) => [key, createPostRoute(mod)]),
) as Record<string, PostRouteComponent>;

const clientRoutes = Object.fromEntries(
  Object.entries(clientPosts).map(([key, loadPost]) => [
    key,
    lazy(async () => {
      const mod = await loadPost();

      return { default: createPostRoute(mod) };
    }),
  ]),
) as Record<string, PostRouteComponent>;

const routes = import.meta.env.SSR ? serverRoutes : clientRoutes;

export default function PostPage(props: Props) {
  const { post } = props;

  if (!post) {
    return null;
  }

  const PostRoute = routes[\`${contentDirImportPath}/\${post.slug}.mdx\`];

  if (!PostRoute) {
    return null;
  }

  return (
    <Suspense fallback={null}>
      <PostRoute {...props} />
    </Suspense>
  );
}
`,
  );

  writeFileIfChanged(
    join(pagesDir, '[slug].server.ts'),
    `${generatedHeader}import blogConfig from 'void-blog/blog-config';
import allPosts from 'void-blog/posts';
import {
  createPostHead,
  createPostLoader,
  type BlogPostLoaderProps,
} from 'void-blog/server';

export type Props = BlogPostLoaderProps;

export const prerender = true;

export function getPrerenderPaths() {
  return allPosts.map(({ slug }) => ({ slug }));
}

export const loader = createPostLoader({ posts: allPosts });
export const head = createPostHead(blogConfig);
`,
  );
}

function generateMarkdownPosts({
  config,
  posts,
  root,
}: {
  config: BlogGeneratedConfig;
  posts: ReadonlyArray<BlogPost>;
  root: string;
}) {
  const outDir = join(root, 'public', config.routeBase.replace(/^\/+/, ''));

  if (!config.markdown) {
    if (existsSync(outDir)) {
      for (const file of readdirSync(outDir)) {
        if (file.endsWith('.md')) {
          rmSync(join(outDir, file), { force: true });
        }
      }
    }

    return;
  }

  const expectedFiles = new Set(posts.map(({ slug }) => `${slug}.md`));

  mkdirSync(outDir, { recursive: true });

  for (const file of readdirSync(outDir)) {
    if (file.endsWith('.md') && !expectedFiles.has(file)) {
      rmSync(join(outDir, file), { force: true });
    }
  }

  for (const { slug, title } of posts) {
    const source = readFileSync(
      join(root, config.contentDir, `${slug}.mdx`),
      'utf8',
    );
    const { content } = matter(source);
    const markdown = `# ${title || slug} - ${config.site.name}\n${content}`;

    writeFileIfChanged(join(outDir, `${slug}.md`), markdown);
  }
}

function generateFeed({
  config,
  posts,
  root,
}: {
  config: BlogGeneratedConfig;
  posts: ReadonlyArray<BlogPost>;
  root: string;
}) {
  if (!config.feed) {
    return;
  }

  const getGeneratedOGImage = (slug: string) =>
    `${config.site.url}/og/${slug}.png`;
  const getPostImage = (post: BlogPost) =>
    post.image ??
    (config.ogImage ? getGeneratedOGImage(post.slug) : config.site.socialImage);
  const getPostURL = (slug: string) =>
    `${config.site.url}${config.routeBase}/${slug}`;

  const formatItem = (post: BlogPost) => {
    const { date, description: initialDescription, slug, title } = post;
    const description = `${initialDescription} Read the full post at ${getPostURL(slug)}.`;
    const image = getPostImage(post);
    const imageMarkup = image
      ? `<img src="${escapeXml(image)}" alt="${escapeXml(title)}" />
`
      : '';

    return `<item>
<title>${escapeXml(title)}</title>
<link>${escapeXml(getPostURL(slug))}</link>
<guid>${escapeXml(getPostURL(slug))}</guid>
<description>${escapeXml(description)}</description>
<content:encoded><![CDATA[${imageMarkup}${description}]]></content:encoded>
<pubDate>${new Date(date).toUTCString()}</pubDate>
</item>
`;
  };

  writeFileIfChanged(
    join(root, 'public/feed.xml'),
    `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">
<channel>
<title>${escapeXml(config.site.name)}</title>
<link>${escapeXml(config.site.url)}</link>
<description>${escapeXml(config.site.description)}</description>
<lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
<language>${escapeXml(config.site.language ?? 'en-US')}</language>
<atom:link href="${escapeXml(`${config.site.url}/feed.xml`)}" rel="self" type="application/rss+xml" />
${posts.map(formatItem).join('')}</channel>
</rss>
`,
  );
}

function generateSitemap({
  config,
  posts,
  root,
}: {
  config: BlogGeneratedConfig;
  posts: ReadonlyArray<BlogPost>;
  root: string;
}) {
  if (!config.sitemap) {
    return;
  }

  const urls = [
    {
      lastmod: new Date().toISOString(),
      loc: config.site.url,
    },
    ...posts.flatMap(({ date, slug }) => {
      const lastmod = new Date(date).toISOString();
      const postUrl = `${config.site.url}${config.routeBase}/${slug}`;

      return [
        {
          lastmod,
          loc: postUrl,
        },
        ...(config.markdown
          ? [
              {
                lastmod,
                loc: `${postUrl}.md`,
              },
            ]
          : []),
      ];
    }),
  ];

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    ({ lastmod, loc }) =>
      `<url><loc>${escapeXml(loc)}</loc><lastmod>${lastmod}</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>`,
  )
  .join('\n')}
</urlset>
`;

  writeFileIfChanged(join(root, 'public/sitemap.xml'), sitemap);
}

function generateLlmsTxt({
  config,
  posts,
  root,
}: {
  config: BlogGeneratedConfig;
  posts: ReadonlyArray<BlogPost>;
  root: string;
}) {
  if (!config.llmsTxt) {
    return;
  }

  const llms = `# ${config.site.name}

> ${config.site.description}

${
  config.markdown
    ? `## Markdown Posts
${posts
  .map(
    ({ slug, title }) =>
      `- [${title}](${config.site.url}${config.routeBase}/${slug}.md)`,
  )
  .join('\n')}

`
    : ''
}## HTML Posts
${posts
  .map(
    ({ slug, title }) =>
      `- [${title}](${config.site.url}${config.routeBase}/${slug})`,
  )
  .join('\n')}
`;

  writeFileIfChanged(join(root, 'public/llms.txt'), llms);
  mkdirSync(join(root, 'public/.well-known'), { recursive: true });
  writeFileIfChanged(join(root, 'public/.well-known/llms.txt'), llms);
}

export async function generateOgImages({
  config,
  posts,
  root,
}: {
  config: BlogGeneratedConfig;
  posts?: ReadonlyArray<BlogPost>;
  root: string;
}) {
  if (!config.ogImage) {
    return;
  }

  const size = { height: 630, width: 1200 };
  const publishedPosts =
    posts ?? getAllPublishedPosts(readPosts({ config, root }));
  const outDir = join(root, 'public', 'og');

  mkdirSync(outDir, { recursive: true });

  const Og = ({
    theme,
    title,
  }: {
    theme?: BlogOGImageTheme;
    title: string;
  }) => {
    let background = '#ffffff';
    let foreground = 'rgb(61, 135, 245)';

    if (theme === 'dark') {
      background = 'rgb(20, 20, 20)';
      foreground = 'rgb(94, 159, 255)';
    } else if (theme === 'purple') {
      foreground = 'rgb(168, 85, 247)';
    } else if (theme === 'emerald') {
      foreground = 'rgb(16, 185, 129)';
    } else if (theme === 'pink') {
      foreground = 'rgb(236, 72, 153)';
    } else if (theme === 'fuchsia') {
      foreground = 'rgb(225, 42, 251)';
    }

    const secondary = 'rgba(107, 114, 128, 0.75)';

    return createElement(
      'div',
      {
        style: {
          alignItems: 'flex-start',
          backgroundColor: background,
          display: 'flex',
          flexDirection: 'column',
          fontFamily: 'SalesforceSans, system-ui, sans-serif',
          height: '630px',
          justifyContent: 'flex-start',
          padding: '80px 100px',
          position: 'relative',
          textAlign: 'left',
          width: '1200px',
        },
      },
      createElement(
        'div',
        {
          style: {
            color: foreground,
            fontSize: '96px',
            fontWeight: 800,
            letterSpacing: '0.025em',
            lineHeight: 1.1,
            marginTop: '64px',
            maxWidth: '1000px',
            wordWrap: 'break-word',
          },
        },
        title.slice(0, 140),
      ),
      createElement(
        'div',
        {
          style: {
            bottom: '60px',
            color: secondary,
            fontSize: '42px',
            fontWeight: 500,
            position: 'absolute',
            right: '80px',
          },
        },
        new URL(config.site.url).host,
      ),
    );
  };

  const fontPath = join(
    root,
    'public/fonts/salesforce/SalesforceSans-Semibold.woff',
  );
  const font = readFileIfExists(fontPath);

  if (!font) {
    console.warn(
      `Skipping Open Graph image generation because ${fontPath} does not exist.`,
    );
    return;
  }

  const generateOGImage = async (title: string, theme?: BlogOGImageTheme) => {
    const svg = await satori(createElement(Og, { theme, title }), {
      fonts: [
        {
          data: readFileSync(fontPath),
          name: 'SalesforceSans',
          style: 'normal',
          weight: 400,
        },
      ],
      height: size.height,
      width: size.width,
    });

    return new Resvg(svg, {
      fitTo: { mode: 'width', value: size.width },
    })
      .render()
      .asPng();
  };

  await Promise.all(
    publishedPosts.map(async (post) => {
      const title =
        (typeof post.title === 'string' && post.title.trim()) || post.slug;
      const theme = post.type
        ? getPostTypeColorName(post.type, config)
        : 'light';
      const png = await generateOGImage(title, theme);

      writeFileSync(join(outDir, `${post.slug}.png`), png);
    }),
  );
}

export function generateContent({
  config,
  configImport,
  log,
  root,
  routeComponentImports,
}: BlogGenerateContentOptions) {
  if (!configImport && config.mdxComponents) {
    throw new Error(
      'Blog configs with `mdxComponents` must be importable. Move the config to `blog.config.ts` or pass `configImport` to `voidBlog()`.',
    );
  }

  const generatedConfig = toGeneratedConfig(config);
  const posts = readPosts({ config: generatedConfig, root });
  const publishedPosts = getAllPublishedPosts(posts);

  generatePostPages({
    config: generatedConfig,
    configImport,
    posts,
    root,
    routeComponentImports,
  });
  generateMarkdownPosts({
    config: generatedConfig,
    posts: publishedPosts,
    root,
  });
  generateFeed({ config: generatedConfig, posts: publishedPosts, root });
  generateSitemap({ config: generatedConfig, posts: publishedPosts, root });
  generateLlmsTxt({ config: generatedConfig, posts: publishedPosts, root });

  if (log !== false) {
    console.log(styleText('green', '✔ Generated void-blog content.'));
  }

  return { config: generatedConfig, posts, publishedPosts };
}
